### ISSUE TITLE
path.join is not a function

### ISSUE THREAD

**Issue by architelos** [Androz2091/easy-json-database#13]
TypeError: path.join is not a function
    at EasyJsonDB.makeSnapshot (D:\Khanh\vscode\recommendations\node_modules\easy-json-database\index.js:87:31)
    at Timeout._onTimeout (D:\Khanh\vscode\recommendations\node_modules\easy-json-database\index.js:60:22)

**Comment by pashoo2** [comment]
The same

**Comment by pashoo2** [comment]
![image](https://github.com/Androz2091/easy-json-database/assets/11247503/2eab542f-d398-477b-b074-df946edbe758)
It seems the author absolutely doesn't care about this module. The following code doesn't even respect the NodeJS FS API
