### ISSUE TITLE
Is not a function: key.split is not a function

### ISSUE THREAD

**Issue by s-pl** [Androz2091/easy-json-database#6]
Im getting this error while im trying to run my project on my virtual machine: 
```
TypeError: key.split is not a function
    at setNestedProperty (C:\Users\Sapol\Desktop\CliGame\node_modules\easy-json-database\index.js:4:28)
    at EasyJsonDB.set (C:\Users\Sapol\Desktop\CliGame\node_modules\easy-json-database\index.js:129:9)
    at C:\Users\Sapol\Desktop\CliGame\index.js:22:6
    at Layer.handle [as handle_request] (C:\Users\Sapol\Desktop\CliGame\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Sapol\Desktop\CliGame\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Sapol\Desktop\CliGame\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Sapol\Desktop\CliGame\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Sapol\Desktop\CliGame\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\Sapol\Desktop\CliGame\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Sapol\Desktop\CliGame\node_modules\express\lib\router\index.js:275:10)
```
You can see my code here: https://hastebin.com/yezopozehu.js

**Comment by s-pl** [comment]
As the developer is not solving my problem, if you are getting this problem just do this:
`npm uninstall easy-json-database
npm install easy-json-database@1.4.0`
This uninstall´s the package and install´s it with the 1.4.0 version.
